package com.dwpg.simulator.entity;

public enum AuditEventType {
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    AUTHORIZATION_FAILURE,
    WALLET_CREATED,
    FUNDS_ADDED,
    PAYMENT_INITIATED,
    PAYMENT_CONFIRMED,
    PAYMENT_FAILED,
    PAYMENT_REFUNDED,
    REPLAY_DETECTED,
    DUPLICATE_PAYMENT,
    SUSPICIOUS_ACTIVITY,
    OAUTH_LOGIN_SUCCESS,
    UPI_PAYMENT_INITIATED,
    UPI_PAYMENT_CONFIRMED,
    UPI_PAYMENT_FAILED
}
