apiVersion: v1
kind: Secret
metadata:
  name: dwpg-secrets
  namespace: dwpg
type: Opaque
stringData:
  MARIADB_USER: "dwpg_user"
  MARIADB_PASSWORD: "SimulatedK8sPass123!"
  MARIADB_ROOT_PASSWORD: "SimulatedK8sRoot123!"
  JWT_SECRET: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
  ADMIN_INITIAL_PASSWORD: "Admin@K8sSecure123!"
